# Generated by Django 2.2.5 on 2019-09-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190924_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='acadm_council',
        ),
        migrations.RemoveField(
            model_name='member',
            name='col_council',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dep_council',
        ),
        migrations.RemoveField(
            model_name='member',
            name='skl_council',
        ),
        migrations.AddField(
            model_name='member',
            name='academic_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.Academic_council'),
        ),
        migrations.AddField(
            model_name='member',
            name='college_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.College_council'),
        ),
        migrations.AddField(
            model_name='member',
            name='department_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.Department_council'),
        ),
        migrations.AddField(
            model_name='member',
            name='school_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.School_council'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.Student_category'),
        ),
        migrations.DeleteModel(
            name='Student_cat',
        ),
    ]
