# Generated by Django 2.2.5 on 2019-09-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190924_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='account.COLLEGE'),
        ),
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='account.SCHOOL'),
        ),
        migrations.AlterField(
            model_name='level',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='account.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='member',
            name='academic_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.ACADEMIC_COUNCIL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.CATEGORY'),
        ),
        migrations.AlterField(
            model_name='member',
            name='college_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.COLLEGE_COUNCIL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.DEPARTMENT_COUNCIL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.LEVEL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.SCHOOL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='school_council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.SCHOOL_COUNCIL'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='account.STUDENT_CATEGORY'),
        ),
        migrations.AlterField(
            model_name='school',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='account.COLLEGE'),
        ),
    ]
