# Generated by Django 2.2.5 on 2019-09-26 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_auto_20190926_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=20)),
                ('regNo', models.IntegerField()),
                ('lecturer', models.CharField(max_length=20)),
                ('staffId', models.IntegerField()),
                ('college_council', models.CharField(max_length=30)),
                ('academic_council', models.CharField(max_length=30)),
                ('school_council', models.CharField(max_length=30)),
                ('department_council', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
