# Generated by Django 2.2.5 on 2019-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20190926_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='regNo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='staffId',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
